// <auto-generated />
using System;
using GestionEspaces.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionEspaces.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GestionEspacesDbContext))]
    [Migration("20260813142018_RemoveReservations")]
    partial class RemoveReservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Actif", b =>
                {
                    b.Property<int>("IdActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdActif"));

                    b.Property<DateTime?>("DateAchat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marque")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modele")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdActif");

                    b.HasIndex("NumeroSerie")
                        .IsUnique()
                        .HasFilter("[NumeroSerie] IS NOT NULL");

                    b.ToTable("Actifs", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.AffectationActif", b =>
                {
                    b.Property<int>("IdAffectationActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectationActif"));

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActif")
                        .HasColumnType("int");

                    b.Property<int>("IdAgent")
                        .HasColumnType("int");

                    b.HasKey("IdAffectationActif");

                    b.HasIndex("IdActif")
                        .IsUnique()
                        .HasFilter("[DateFin] IS NULL");

                    b.HasIndex("IdAgent");

                    b.ToTable("AffectationsActif", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.AffectationPoste", b =>
                {
                    b.Property<int>("IdAffectationPoste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAffectationPoste"));

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAgent")
                        .HasColumnType("int");

                    b.Property<int>("IdBureau")
                        .HasColumnType("int");

                    b.HasKey("IdAffectationPoste");

                    b.HasIndex("IdAgent")
                        .IsUnique()
                        .HasFilter("[DateFin] IS NULL");

                    b.HasIndex("IdBureau")
                        .IsUnique()
                        .HasFilter("[DateFin] IS NULL");

                    b.ToTable("AffectationsPoste", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Agent", b =>
                {
                    b.Property<int>("IdAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgent"));

                    b.Property<DateTime?>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departement")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Fonction")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Matricule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdAgent");

                    b.HasIndex("Matricule")
                        .IsUnique();

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Batiment", b =>
                {
                    b.Property<int>("IdBatiment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBatiment"));

                    b.Property<int>("IdSite")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NombreEtages")
                        .HasColumnType("int");

                    b.Property<float>("Superficie")
                        .HasColumnType("real");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdBatiment");

                    b.HasIndex("IdSite");

                    b.ToTable("Batiments", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Bureau", b =>
                {
                    b.Property<int>("IdBureau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBureau"));

                    b.Property<int>("Capacite")
                        .HasColumnType("int");

                    b.Property<int>("Etage")
                        .HasColumnType("int");

                    b.Property<int>("IdBatiment")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<float>("Superficie")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdBureau");

                    b.HasIndex("IdBatiment", "Numero")
                        .IsUnique();

                    b.ToTable("Bureaux", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Site", b =>
                {
                    b.Property<int>("IdSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSite"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("IdSite");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sites", (string)null);
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.AffectationActif", b =>
                {
                    b.HasOne("GestionEspaces.Domain.Entities.Actif", "Actif")
                        .WithMany("Affectations")
                        .HasForeignKey("IdActif")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionEspaces.Domain.Entities.Agent", "Agent")
                        .WithMany("AffectationsActif")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Actif");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.AffectationPoste", b =>
                {
                    b.HasOne("GestionEspaces.Domain.Entities.Agent", "Agent")
                        .WithMany("AffectationsPoste")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GestionEspaces.Domain.Entities.Bureau", "Bureau")
                        .WithMany("Affectations")
                        .HasForeignKey("IdBureau")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Bureau");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Batiment", b =>
                {
                    b.HasOne("GestionEspaces.Domain.Entities.Site", "Site")
                        .WithMany("Batiments")
                        .HasForeignKey("IdSite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Bureau", b =>
                {
                    b.HasOne("GestionEspaces.Domain.Entities.Batiment", "Batiment")
                        .WithMany("Bureaux")
                        .HasForeignKey("IdBatiment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batiment");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Site", b =>
                {
                    b.OwnsOne("GestionEspaces.Domain.ValueObjects.AdresseSite", "Adresse", b1 =>
                        {
                            b1.Property<int>("SiteIdSite")
                                .HasColumnType("int");

                            b1.Property<string>("CodePostal")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("AdresseCodePostal");

                            b1.Property<string>("Pays")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("AdressePays");

                            b1.Property<string>("Rue")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("nvarchar(250)")
                                .HasColumnName("AdresseRue");

                            b1.Property<string>("Ville")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("AdresseVille");

                            b1.HasKey("SiteIdSite");

                            b1.ToTable("Sites");

                            b1.WithOwner()
                                .HasForeignKey("SiteIdSite");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Actif", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Agent", b =>
                {
                    b.Navigation("AffectationsActif");

                    b.Navigation("AffectationsPoste");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Batiment", b =>
                {
                    b.Navigation("Bureaux");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Bureau", b =>
                {
                    b.Navigation("Affectations");
                });

            modelBuilder.Entity("GestionEspaces.Domain.Entities.Site", b =>
                {
                    b.Navigation("Batiments");
                });
#pragma warning restore 612, 618
        }
    }
}
